# ================================================================
# RHCE Lab Inventory
# ================================================================

[controllers]
controller ansible_host=192.168.56.10 ansible_connection=local

[nodes]
servera ansible_host=192.168.56.11
serverb ansible_host=192.168.56.12
serverc ansible_host=192.168.56.13
serverd ansible_host=192.168.56.14
servere ansible_host=192.168.56.15

[infrastructure]
reposerver  ansible_host=192.168.56.20
storage-lab ansible_host=192.168.56.30

[lab:children]
nodes
infrastructure

[all:vars]
ansible_user                 = ansi_user
ansible_ssh_private_key_file = /home/ansi_user/.ssh/id_rsa
ansible_python_interpreter   = /usr/bin/python3
